image: zazukoians/node-java-jena
before_script:
#  - scripts/bootstrap.sh
  - npm install


# stages
stages:
- fetch
- convert
- staging
- validate
- post

# jobs

fetch_didok_job:
  stage: fetch
  script:
    - npm run fetch-didok
  artifacts:
    paths:
      - input/didok.csv
    expire_in: 30 minutes

fetch_rollmaterial_job:
  stage: fetch
  script:
    - npm run fetch-rollmaterial
  artifacts:
    paths:
      - input/rollmaterial.csv
    expire_in: 30 minutes

convert_job:
  stage: convert
  script:
    - npm run convert
    - npm run clean-didok
    - npm run clean-rollmaterial
    - npm run void-timestamp
  artifacts:
    paths:
      - target/didok-clean.nt
      - target/rollmaterial-clean.nt
      - target/void.ttl
    expire_in: 1 hour

staging_tdb_job:
  stage: staging
  script:
    - npm run tdb-load
    - npm run tdb-query
    - npm run tdb-dump
  artifacts:
    paths:
      - target/everything.nt.gz
    expire_in: 1 day

validate_riot_job:
  stage: validate
  script:
    - npm run validate-riot
  artifacts:
    paths:
      - target/everything.nt.gz
    expire_in: 1 day

post_test_job:
  stage: post
#  only:
#    - tags
#    - develop
  script:
    - npm run store-s3
    